version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: jobs_postgres
    restart: always
    environment:
      POSTGRES_USER: jobs_user
      POSTGRES_PASSWORD: jobs_password
      POSTGRES_DB: jobs_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
